### ISSUE TITLE
Node.js  - Unsupported DID method: 'muport'

### ISSUE THREAD

**Issue by Garik-** [3box/muport-did-resolver#13]
Hi, I wrote simple code.
```JS
const resolve = require('did-resolver').default
const registerResolver = require('muport-did-resolver')

registerResolver()
resolve('did:muport:QmRhjfL4HLdB8LovGf1o43NJ8QnbfqmpdnTuBvZTewnuBV').then(doc => console.log(doc))
```
node code.js -> `Unsupported DID method: 'muport'`
If rewrite function register 
```JS
return resolve
```
and wrote in my code 
```JS
const methodResolve = registerResolver()
registerMethod('muport', methodResolve)
```
Script started working, because `var REGISTRY` in did-resolver NOT a global object

**Comment by oed** [comment]
Strange, what version of `muport-did-resolver` and `did-resolver` do you have? This should work!

**Comment by Garik-** [comment]
```JSON
"did-resolver": "^0.0.6",
"muport-did-resolver": "^0.2.0"
```

**Comment by oed** [comment]
Can you try updating `muport-did-resolver` to `0.3.0` and see if it helps?

**Comment by Garik-** [comment]
Yes it helped code works, thanks :)

**Comment by oed** [comment]
Great! :D
